routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\UserMenuController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\UserSubMenuController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// sentry
Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// buatan
Route::get('/role/{role}/access', [UserRoleController::class, 'access']);
Route::post('profile/reset/{id}', [UserProfileController::class, 'resetProfile']);
Route::get('profile/change-password', [UserProfileController::class, 'changePassword'])->name('change-password.index');
Route::patch('profile/change-password/{id}', [UserProfileController::class, 'changeProccess'])->name('profile.change-password');

// // resource
Route::resource('user', UserController::class);
Route::resource('menu', UserMenuController::class);
Route::resource('submenu', UserSubMenuController::class);
Route::resource('role', UserRoleController::class);
Route::resource('profile', UserProfileController::class);

resources/views/submenu/create.blade.php
@extends('layouts.main')
@section('title', 'Submenu Management')
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">Submenu</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ url('submenu') }}" class="text-muted text-hover-primary">Submenu</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<form action="{{ route('submenu.store') }}" method="post" class="form-group">
							@csrf
							<div class="form-group mb-5">
								<label for="menu_id">Menu</label>
								<select class="form-select form-select-lg" id="menu_id" data-control="select2" data-placeholder="Pilih Menu" data-allow-clear="true" name="menu_id">
									<option></option>
									@foreach ($menu as $mn)
										<option value="{{ $mn->id }}">{{ $mn->name }}</option>
									@endforeach
								</select>
							</div>
							<div class="form-group mb-5">
								<label for="name">Submenu</label>
								<input type="text" class="form-control" id="name" aria-describedby="name" placeholder="Masukan Submenu" name="name">
								<small id="name" class="form-text text-muted">Gunakan submenu yang spesifik dan membantu</small>
							</div>
							<div class="form-group mb-5">
								<label for="url">URL</label>
								<input type="text" class="form-control" id="url" aria-describedby="url" placeholder="Masukan Submenu" name="url">
								<small id="url" class="form-text text-muted">Gunakan url yang benar</small>
							</div>
							<div class="form-group mb-5">
								<label for="icon">Icon</label>
								<input type="text" class="form-control" id="icon" aria-describedby="icon" placeholder="Contoh: fas fa-home" name="icon">
								<small id="icon" class="form-text text-muted">Gunakan Bootstrap Icon / Fontawesome</small>
							</div>
							<div class="form-group mb-5">
								<label for="is_active">Status</label>
								<select class="form-select form-select-lg" id="is_active" data-control="select2" data-placeholder="Pilih Status" data-allow-clear="true" name="is_active">
									<option></option>
									<option value="1">Aktif</option>
									<option value="0">Tidak Aktif</option>
								</select>
							</div>
							
							<button type="submit" class="btn btn-primary">Submit</button>
							<button type="button" class="btn btn-warning" onclick="history.back()">Back</button>
						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/submenu/edit.blade.php
@extends('layouts.main')
@section('title', 'Submenu Management')
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">Submenu</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ url('submenu') }}" class="text-muted text-hover-primary">Submenu</a>
						</li>
						<li class="breadcrumb-item text-dark">Edit</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<form action="{{ url('submenu/'. $submenu->id) }}" method="post" class="form-group">
							@csrf
							@method('patch')
							<div class="form-group mb-5">
								<label for="menu_id">Menu</label>
								<select class="form-select form-select-lg" id="menu_id" data-control="select2" data-placeholder="Pilih Menu" data-allow-clear="true" name="menu_id">
									<option value="{{ $submenu->menu_id }}">{{ $submenu->menu->name }}</option>
									@foreach ($menu as $mn)
										<option value="{{ $mn->id }}">{{ $mn->name }}</option>
									@endforeach
								</select>
							</div>
							<div class="form-group mb-5">
								<label for="name">Submenu</label>
								<input type="text" class="form-control" id="name" aria-describedby="name" placeholder="Masukan Submenu" name="name" value="{{ $submenu->name }}">
								<small id="name" class="form-text text-muted">Gunakan submenu yang spesifik dan membantu</small>
							</div>
							<div class="form-group mb-5">
								<label for="url">URL</label>
								<input type="text" class="form-control" id="url" aria-describedby="url" placeholder="Masukan Submenu" name="url" value="{{ $submenu->url }}">
								<small id="url" class="form-text text-muted">Gunakan url yang benar</small>
							</div>
							<div class="form-group mb-5">
								<label for="icon">Icon</label>
								<input type="text" class="form-control" id="icon" aria-describedby="icon" placeholder="Contoh: fas fa-home" name="icon" value="{{ $submenu->icon }}">
								<small id="icon" class="form-text text-muted">Gunakan Bootstrap Icon / Fontawesome</small>
							</div>
							<div class="form-group mb-5">
								<label for="is_active">Status</label>
								<select class="form-select form-select-lg" id="is_active" data-control="select2" data-placeholder="Pilih Status" data-allow-clear="true" name="is_active">
									<option value="{{ $submenu->is_active }}">{{ $submenu->is_active == '1' ? 'Aktif' : 'Tidak Aktif'}}</option>
									<option value="1">Aktif</option>
									<option value="0">Tidak Aktif</option>
								</select>
							</div>
							
							<button type="submit" class="btn btn-primary">Submit</button>
							<button type="button" class="btn btn-warning" onclick="history.back()">Back</button>
						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/submenu/index.blade.php
@extends('layouts.main')
@section('title', 'Submenu Management')
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('/submenu') }}" class="text-muted text-hover-primary">Submenu</a>
						</li>
						<li class="breadcrumb-item text-dark">Submenu Management</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<!--begin::Alert-->                                        
					
					<!--end::Alert-->
						<div class="table-responsive">
							<a href="{{ url('/submenu/create') }}" class="btn btn-primary mb-3" >Tambah Submenu Baru</a>
							@if (session('status'))
								<div class="alert alert-primary">
									{{ session('status') }}
								</div>
							@endif
							<table class="table table-striped table-hover gy-7 gs-7 text-center">
								<thead>
									<tr class="fw-bold fs-6 text-gray-800 border-bottom-2 border-gray-200">
										<th>No</th>
										<th>Menu</th>
										<th>Submenu</th>
										<th>Icon</th>
										<th>Aksi</th>
										
									</tr>
								</thead>
								<tbody>                                                 
									@foreach($submenu as $sm)
										<tr>
											<td>{{ $loop->iteration }}</td>
											<td>{{ $sm->menu->name }}</td>
											<td>{{ $sm->name }}</td>
											<td><i class="{{ $sm->icon }} fs-2"></i></td>
											<td>
												<form action="{{ url('submenu'. '/' .$sm->id) }}" class="form-group" method="post">
													@csrf
													@method('delete')
													<a href="{{ 'submenu/'. $sm->id . '/edit' }}" class="badge badge-primary">Edit</a>
													<button type="submit" class="badge badge-danger btn-delete" style="border:none">Delete</button>
												</form>
											</td>          
										</tr>       
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection

@section('scripts')
	<script type="text/javascript">


		$('body').on('click', '.btn-delete', function(event) {
			event.preventDefault();

			var form = $(this).closest('form');

			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				icon: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!'
			}).then((result) => {
				if (result.isConfirmed) {
					form.submit();
				}
			})


		})

		

	</script>
@endsection