routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\UserMenuController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\UserSubMenuController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// sentry
Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// buatan
Route::get('/role/{role}/access', [UserRoleController::class, 'access']);
Route::post('profile/reset/{id}', [UserProfileController::class, 'resetProfile']);
Route::get('profile/change-password', [UserProfileController::class, 'changePassword'])->name('change-password.index');
Route::patch('profile/change-password/{id}', [UserProfileController::class, 'changeProccess'])->name('profile.change-password');

// // resource
Route::resource('user', UserController::class);
Route::resource('menu', UserMenuController::class);
Route::resource('submenu', UserSubMenuController::class);
Route::resource('role', UserRoleController::class);
Route::resource('profile', UserProfileController::class);

resources/views/role/access.blade.php
@extends('layouts.main')
@section('title', 'Role Management')
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">Role</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ url('role') }}" class="text-muted text-hover-primary">Role</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<form action="" method="post" class="form-group">
							@csrf
							<div class="form-group mb-5">
								<label for="role_id">Role</label>
								<input type="text" class="form-control" id="role_id" aria-describedby="role_id" placeholder="Masukan Role" name="role_id" value="{{ $role->name }}" readonly>
							</div>
							<div class="form-group mb-5">
								<label for="role_id">Access Menu</label>
                                @foreach ($menu as $mn)
                                    <div class="form-check form-check-custom form-check-solid mb-3 mt-2">
										@php
											$checked = '';
										@endphp
										@foreach ($mn->access as $access)
											@if($access->role_id == $role->id) 
												@php
													$checked = 'checked="checked"';
												@endphp
											@endif											
										@endforeach
                                        <input class="form-check-input" type="checkbox" id="check{{ $loop->iteration }}" name="access[]" value="{{ $mn->id}}" {{ $checked }}/>
                                        <label class="form-check-label" for="check{{ $loop->iteration }}">
                                            {{ $mn->name }}
                                        </label>
                                    </div>
                                @endforeach
							</div>
							{{-- <button type="submit" class="btn btn-primary">Submit</button> --}}
							<button type="button" class="btn btn-warning" onclick="history.back()">Back</button>
						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
        });

        $('.form-check-input').on('click', function(){
            var menu_id = $(this).val();
            var role_id = `{{ $role->id }}`;

            $.ajax({
                url: `{{ route('api.accessProcess') }}`,
                data: {menu_id: menu_id, role_id:role_id},
                success: function(response) {
                    $( ".sidebar-main" ).load(window.location.href + " .sidebar-main" );
                }
            });

        });

    </script>
@endsection

resources/views/role/create.blade.php
@extends('layouts.main')
@section('title', 'Role Management')
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">Role</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ url('role') }}" class="text-muted text-hover-primary">Role</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<form action="{{ route('role.store') }}" method="post" class="form-group">
							@csrf
							<div class="form-group mb-5">
								<label for="name">Role</label>
								<input type="text" class="form-control" id="name" aria-describedby="name" placeholder="Masukan Role" name="name">
								<small id="name" class="form-text text-muted">Gunakan nama yang spesifik dan membantu</small>
							</div>
							<button type="submit" class="btn btn-primary">Submit</button>
							<button type="button" class="btn btn-warning" onclick="history.back()">Back</button>
						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/role/edit.blade.php
@extends('layouts.main')
@section('title', 'Role Management')
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">Role</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ url('role') }}" class="text-muted text-hover-primary">Role</a>
						</li>
						<li class="breadcrumb-item text-dark">Edit</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<form action="{{ url('role/'. $role->id) }}" method="post" class="form-group">
							@csrf
							@method('patch')
							<div class="form-group mb-5">
								<label for="name">Role</label>
								<input type="text" class="form-control" id="name" aria-describedby="name" placeholder="Masukan Role" name="name" value="{{ $role->name }}">
								<small id="name" class="form-text text-muted">Gunakan nama yang spesifik dan membantu</small>
							</div>
							<button type="submit" class="btn btn-primary">Submit</button>
							<button type="button" class="btn btn-warning" onclick="history.back()">Back</button>
						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/role/index.blade.php
@extends('layouts.main')
@section('title', 'Role Management')
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('/role') }}" class="text-muted text-hover-primary">Role</a>
						</li>
						<li class="breadcrumb-item text-dark">Role Management</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<!--begin::Alert-->                                        
					
					<!--end::Alert-->
						<div class="table-responsive">
							<a href="{{ url('/role/create') }}" class="btn btn-primary mb-3" >Tambah Role Baru</a>
							@if (session('status'))
								<div class="alert alert-primary">
									{{ session('status') }}
								</div>
							@endif
							<table class="table table-striped table-hover gy-7 gs-7 text-center">
								<thead>
									<tr class="fw-bold fs-6 text-gray-800 border-bottom-2 border-gray-200">
										<th>No</th>
										<th>Role</th>
										<th>Aksi</th>
									</tr>
								</thead>
								<tbody>                                                 
									@foreach($role as $rl)
										<tr>
											<td>{{ $loop->iteration }}</td>
											<td>{{ $rl->name }}</td>
											<td>
												<form action="{{ url('role'. '/' .$rl->id) }}" class="form-group" method="post">
													@csrf
													@method('delete')
													<a href="{{ 'role/'. $rl->id . '/edit' }}" class="badge badge-primary">Edit</a>
													<a href="{{ 'role/'. $rl->id . '/access' }}" class="badge badge-warning">Access</a>
													<button type="submit" class="badge badge-danger btn-delete" style="border:none">Delete</button>
												</form>
											</td>          
										</tr>       
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection

@section('scripts')
	<script type="text/javascript">


		$('body').on('click', '.btn-delete', function(event) {
			event.preventDefault();

			var form = $(this).closest('form');

			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				icon: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!'
			}).then((result) => {
				if (result.isConfirmed) {
					form.submit();
				}
			})


		})

		

	</script>
@endsection