routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\UserMenuController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\UserSubMenuController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// sentry
Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// buatan
Route::get('/role/{role}/access', [UserRoleController::class, 'access']);
Route::post('profile/reset/{id}', [UserProfileController::class, 'resetProfile']);
Route::get('profile/change-password', [UserProfileController::class, 'changePassword'])->name('change-password.index');
Route::patch('profile/change-password/{id}', [UserProfileController::class, 'changeProccess'])->name('profile.change-password');

// // resource
Route::resource('user', UserController::class);
Route::resource('menu', UserMenuController::class);
Route::resource('submenu', UserSubMenuController::class);
Route::resource('role', UserRoleController::class);
Route::resource('profile', UserProfileController::class);

app/Models/User.php
<?php

namespace App\Models;

use App\Models\UserRole;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'role_id',
        'name',
        'image',
        'email',
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(UserRole::class, 'role_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\UserRole;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        return view('user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = User::all();
        $role = UserRole::all();
        return view('user.create', compact('user', 'role'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $req = $request->all();

        if($req['password'] != $req['password2']){
            return redirect(route('user.create'))->with('failed', 'Password tidak sama!');
        }

        $req['password'] = Hash::make($req['password']);
        $req['remember_token'] = Str::random(60);
        User::create($req);

        return redirect(route('user.index'))->with('status', 'User baru berhasil ditambahkan!');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $role = UserRole::all();
        return view('user.edit', compact('user', 'role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $req = $request->all();

        $user->update($req);
        
        return redirect(route('user.index'))->with('status', 'User berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect(route('user.index'))->with('status', 'User berhasil dihapus!');
    }
}

resources/views/user/create.blade.php
@extends('layouts.main')
@section('title', 'User Management')
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">User</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ url('/user') }}" class="text-muted text-hover-primary">User</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						@if (session('failed'))
								<div class="alert alert-danger">
									{{ session('failed') }}
								</div>
							@endif
						<form action="{{ route('user.store') }}" method="post" class="form-group">
							@csrf
							<div class="form-group mb-5">
								<label for="role_id">Role</label>
								<select class="form-select form-select-lg" id="role_id" data-control="select2" data-placeholder="Pilih Role" data-allow-clear="true" name="role_id">
									<option></option>
									@foreach ($role as $rl)
										<option value="{{ $rl->id }}">{{ $rl->name }}</option>
									@endforeach
								</select>
							</div>
							<div class="form-group mb-5">
								<label for="name">Nama User</label>
								<input type="text" class="form-control" id="name" aria-describedby="name" placeholder="Masukan Nama User" name="name">
								<small id="name" class="form-text text-muted">Gunakan nama user yang spesifik dan membantu</small>
							</div>
							<div class="form-group mb-5">
								<label for="image">Image</label>
								<input type="text" class="form-control" id="image" aria-describedby="image" name="image" value="default.svg">
							</div>
							<div class="form-group mb-5">
								<label for="email">Email</label>
								<input type="email" class="form-control" id="email" aria-describedby="email" name="email" placeholder="Masukan Email Anda">
							</div>
							<div class="form-group mb-5">
								<label for="password">Password</label>
								<input type="password" class="form-control" id="password" aria-describedby="password" name="password" placeholder="Masukan Password Anda">
							</div>
							<div class="form-group mb-5">
								<label for="password2">Confirm Password</label>
								<input type="password" class="form-control" id="password2" aria-describedby="password2" name="password2" placeholder="Confirm Password">
							</div>
							
							<button type="submit" class="btn btn-primary">Submit</button>
							<button type="button" class="btn btn-warning" onclick="history.back()">Back</button>
						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/user/edit.blade.php
@extends('layouts.main')
@section('title', 'User Management')
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">User</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ url('user') }}" class="text-muted text-hover-primary">User</a>
						</li>
						<li class="breadcrumb-item text-dark">Edit</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<form action="{{ url('user/'. $user->id) }}" method="post" class="form-group">
							@csrf
                            @method('patch')
							<div class="form-group mb-5">
								<label for="role_id">Role</label>
								<select class="form-select form-select-lg" id="role_id" data-control="select2" data-placeholder="Pilih Role" data-allow-clear="true" name="role_id">
									<option value="{{ $user->role_id }}">{{ $user->role->name}}</option>
									@foreach ($role as $rl)
										<option value="{{ $rl->id }}">{{ $rl->name }}</option>
									@endforeach
								</select>
							</div>
							<div class="form-group mb-5">
								<label for="name">Nama User</label>
								<input type="text" class="form-control" id="name" aria-describedby="name" placeholder="Masukan Nama User" name="name" value="{{ $user->name }}">
								<small id="name" class="form-text text-muted">Gunakan nama user yang spesifik dan membantu</small>
							</div>
							<div class="form-group mb-5">
								<label for="image">Image</label>
								<input type="text" class="form-control" id="image" aria-describedby="image" name="image" value="default.svg">
							</div>
							<div class="form-group mb-5">
								<label for="email">Email</label>
								<input type="email" class="form-control" id="email" aria-describedby="email" name="email" placeholder="Masukan Email Anda" value="{{ $user->email }}">
							</div>
							{{-- <div class="form-group mb-5">
								<label for="password">Password</label>
								<input type="password" class="form-control" id="password" aria-describedby="password" name="password" placeholder="Masukan Password Anda">
							</div>
							<div class="form-group mb-5">
								<label for="password2">Confirm Password</label>
								<input type="password" class="form-control" id="password2" aria-describedby="password2" name="password2" placeholder="Confirm Password">
							</div> --}}
							
							<button type="submit" class="btn btn-primary">Submit</button>
							<button type="button" class="btn btn-warning" onclick="history.back()">Back</button>
						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/user/index.blade.php
@extends('layouts.main')
@section('title', 'User Management')
@section('content')
	<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('/user') }}" class="text-muted text-hover-primary">User</a>
						</li>
						<li class="breadcrumb-item text-dark">User Management</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<div class="table-responsive">
							<a href="{{ url('/user/create') }}" class="btn btn-primary mb-3" >Tambah User Baru</a>
							<!--begin::Alert-->
							@if (session('status'))
								<div class="alert alert-primary">
									{{ session('status') }}
								</div>
							@endif
							<!--end::Alert-->
							<table class="table table-striped table-hover gy-7 gs-7 text-center">
								<thead>
									<tr class="fw-bold fs-6 text-gray-800 border-bottom-2 border-gray-200">
										<th>No</th>
										<th>User</th>
										<th>Aksi</th>
										
									</tr>
								</thead>
								<tbody>                                                 
									@foreach($user as $usr)
										<tr>
											<td>{{ $loop->iteration }}</td>
											<td>{{ $usr->name }}</td>
											<td>
												<form action="{{ url('user'. '/' .$usr->id) }}" class="form-group" method="post">
													@csrf
													@method('delete')
													<a href="{{ 'user/'. $usr->id . '/edit' }}" class="badge badge-primary">Edit</a>
													<button type="submit" class="badge badge-danger btn-delete" style="border:none">Delete</button>
												</form>
											</td>          
										</tr>       
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection

@section('scripts')
	<script type="text/javascript">


		$('body').on('click', '.btn-delete', function(event) {
			event.preventDefault();

			var form = $(this).closest('form');

			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				icon: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!'
			}).then((result) => {
				if (result.isConfirmed) {
					form.submit();
				}
			})


		})

		

	</script>
@endsection